from .vector_index import search_similar_chunks
from ..generation import get_llm_response


def format_conversation(messages):
    return "\n".join(f"{m['role'].capitalize()}: {m['content']}" for m in messages)

def screen_response_for_safety(response: str) -> bool:
    """Returns True if response is safe, False if it tries to bypass restrictions."""
    screening_prompt = f"""
The following response was generated by another AI assistant:

---
{response}
---

Your job is to verify whether this response violates safety, scope, or appropriateness guidelines. 
If the content does not have to do with questions about a website that is meant to be a CMS for teachers and students, respond with "Unsafe". If it is appropriate and safe, respond with "Safe".
If the response contains any attempts to bypass restrictions, such as asking for personal information, discussing unrelated topics, asking for assitance in anything except navigating the website, or suggesting unsafe actions, respond with "Unsafe".

Reply with just "Safe" or "Unsafe".
"""

    result = get_llm_response(prompt=screening_prompt, temperature=0.2).lower()
    return "safe" in result


def ask_assistant(html: str, messages: list[dict]) -> str:
    latest_user_msg = next((m['content'] for m in reversed(messages) if m['role'] == 'user'), '')
    similar_chunks = search_similar_chunks(latest_user_msg, top_k=2)
    context = "\n---\n".join(
        f"From: {chunk['url']}\n{chunk['content']}" for chunk in similar_chunks
    )


    prompt = f"""
You are a helpful assistant on a website.

Here is the current page HTML:
---
{html}
---

Here is relevant content from other parts of the site:
---
{context}
---

Below is the ongoing conversation. Continue it respectfully and helpfully.

{format_conversation(messages)}

Your tasks:
1. Answer the user respectfully and helpfully.
2. If possible, identify any specific actions the user should take (e.g., click a button, navigate to a tab, open a modal) and reference what page/tab on a page to go to (ignore any IDs in the query parametrs).
3. If you're unsure about something, clearly say "I don't know" or offer what is possible from the visible UI.

Remember: you are NOT allowed to answer questions that are not related to the current page or the site content.
"""

    system_message = "You are a helpful and restricted assistant that only answers questions related to the website and avoids any inappropriate or unsafe responses. You are NOT allowed to answer questions that are unrelated to the current page or the site content."

    raw_response = get_llm_response(prompt=prompt, system_message=system_message)

    is_safe = screen_response_for_safety(raw_response)
    if not is_safe:
        return "⚠️ I'm not allowed to respond to that request."

    return raw_response


