# Generated by Django 4.2.20 on 2025-03-23 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathways.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='pathways_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='pathways_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='not_started', max_length=50)),
                ('next_chapters', models.ManyToManyField(blank=True, related_name='previous_chapters', to='pathways.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_id', models.CharField(default=pathways.models.generate_join_id, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('students', models.ManyToManyField(related_name='enrolled_classrooms', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='teaching_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('content', 'Content'), ('html', 'HTML'), ('video', 'Video')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('solution', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('answer', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=10000)),
                ('mode', models.CharField(choices=[('strict', 'Strict'), ('casual', 'Casual')], default='casual', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('grade', models.CharField(default='Unspecified', max_length=255)),
                ('learning_goals', models.JSONField(blank=True, default=list)),
                ('progress', models.IntegerField()),
                ('published', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='pathways.classroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('master_scaffold', models.TextField()),
                ('progress', models.FloatField(default=0.0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='pathways.classroom')),
                ('student_roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='pathways.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(blank=True, default=list)),
                ('failed_questions', models.ManyToManyField(blank=True, related_name='failed_in_quizzes', to='pathways.question')),
                ('questions', models.ManyToManyField(related_name='quizzes', to='pathways.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('yt_video', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='not_started', max_length=50)),
                ('learning_goals', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='pathways.chapter')),
                ('content_list', models.ManyToManyField(blank=True, related_name='modules', to='pathways.content')),
                ('next_modules', models.ManyToManyField(blank=True, related_name='previous_modules', to='pathways.module')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Module', to=settings.AUTH_USER_MODEL)),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='pathways.quiz')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_modules', to='pathways.module')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user', 'User'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='pathways.module')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='pathways.module'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='pathways.roadmap'),
        ),
    ]
