# Generated by Django 4.2.21 on 2025-06-16 03:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('organization_admin', 'Organization Admin'), ('admin', 'Admin')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_grade', models.FloatField(blank=True, null=True)),
                ('completion_rate', models.FloatField(blank=True, null=True)),
                ('accuracy_rate', models.FloatField(blank=True, null=True)),
                ('avg_score_per_question', models.FloatField(blank=True, null=True)),
                ('avg_score_per_deliverable', models.FloatField(blank=True, null=True)),
                ('avg_attempts_per_question', models.FloatField(blank=True, null=True)),
                ('skipped_questions', models.IntegerField(blank=True, null=True)),
                ('skipped_rate', models.FloatField(blank=True, null=True)),
                ('mastered_topics', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100))),
                ('struggled_topics', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100))),
                ('avg_time_spent', models.DurationField(blank=True, null=True)),
                ('avg_time_per_question', models.DurationField(blank=True, null=True)),
                ('avg_time_per_deliverable', models.DurationField(blank=True, null=True)),
                ('engagement_score', models.IntegerField(blank=True, null=True)),
                ('lateness_rate', models.FloatField(blank=True, null=True)),
                ('active_days', models.IntegerField(blank=True, null=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('first_active', models.DateTimeField(blank=True, null=True)),
                ('learning_velocity', models.FloatField(blank=True, null=True)),
                ('retention_estimate', models.FloatField(blank=True, null=True)),
                ('procrastination_index', models.FloatField(blank=True, null=True)),
                ('consistency_score', models.FloatField(blank=True, null=True)),
                ('progress_over_time', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('join_id', models.CharField(max_length=20, unique=True)),
                ('details', models.TextField(blank=True)),
                ('analytics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathways.analytics')),
                ('students', models.ManyToManyField(blank=True, related_name='joined_classrooms', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DifficultyBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pathways.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('announcement', 'Announcement'), ('general', 'General')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('grade', models.FloatField()),
                ('engagement_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('solution', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.IntegerField(default=1)),
                ('attempt_count', models.IntegerField(default=0)),
                ('skipped', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('first_correct_attempt', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50)),
                ('learning_goal', models.TextField(blank=True)),
                ('background', models.JSONField(blank=True, default=list)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('analytics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathways.analytics')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pathways.classroom')),
                ('student_analytics', models.ManyToManyField(blank=True, related_name='unit_student_analytics', to='pathways.analytics')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.TextField(blank=True)),
                ('analytics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathways.analytics')),
                ('student_analytics', models.ManyToManyField(blank=True, related_name='week_student_analytics', to='pathways.analytics')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='pathways.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=1)),
                ('skipped', models.BooleanField(default=False)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('late', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.ManyToManyField(blank=True, to='pathways.comment')),
                ('submission', models.ManyToManyField(blank=True, to='pathways.material')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('test', 'Test'), ('checkin', 'Check-in'), ('resource', 'Resource')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('out_of', models.IntegerField(blank=True, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('time_limit', models.DurationField(blank=True, null=True)),
                ('show_correct_answers', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('handouts', models.ManyToManyField(blank=True, to='pathways.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('test', 'Test'), ('checkin', 'Check-in'), ('resource', 'Resource')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('out_of', models.IntegerField(blank=True, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('handouts', models.ManyToManyField(blank=True, to='pathways.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissedDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_items', to='pathways.attendance')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_viewed', models.DurationField(blank=True, null=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathways.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'material')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='types',
            field=models.ManyToManyField(related_name='materials', to='pathways.materialtype'),
        ),
        migrations.AddField(
            model_name='material',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_materials', through='pathways.MaterialView', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('test', 'Test'), ('checkin', 'Check-in'), ('resource', 'Resource')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('out_of', models.IntegerField(blank=True, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('handouts', models.ManyToManyField(blank=True, to='pathways.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pathways.material'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathways.comment'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('test', 'Test'), ('checkin', 'Check-in'), ('resource', 'Resource')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('out_of', models.IntegerField(blank=True, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('max_responses', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('handouts', models.ManyToManyField(blank=True, to='pathways.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='pathways.classroom'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analytics',
            name='easy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='easy_for', to='pathways.difficultybreakdown'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='hard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hard_for', to='pathways.difficultybreakdown'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='medium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medium_for', to='pathways.difficultybreakdown'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'classroom', 'date')},
        ),
    ]
