# Generated by Django 4.2.20 on 2025-05-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='block_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('learning_objectives', 'Learning Objectives'), ('definition', 'Definition'), ('concept_explanation', 'Concept Explanation'), ('worked_example', 'Worked Example'), ('practice_exercise', 'Practice Exercise'), ('visual_aid', 'Visual Aid'), ('real_world_link', 'Real World Link'), ('misconception', 'Misconception'), ('comparison', 'Comparison'), ('summary', 'Summary'), ('reflection', 'Reflection'), ('challenge_problem', 'Challenge Problem'), ('interactive_element', 'Interactive Element'), ('video', 'Video')], default='content', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='styling',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='transition_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
