# Generated by Django 4.2.20 on 2025-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice')], max_length=20),
        ),
    ]
