# Generated by Django 4.2.20 on 2025-03-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='details',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
