# Generated by Django 4.2.20 on 2025-03-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
