# Generated by Django 4.2.21 on 2025-05-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_content_block_type_content_styling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_learning_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chapter',
            name='required_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_chapters', to='pathways.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Default Quiz', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], max_length=20),
        ),
    ]
